### ISSUE TITLE
임신출산 컨텐츠 engage 개선

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#24]
네이버에서 [앙쥬]를 검색하여 테스트 센터에 방문한 세션이 컨텐츠에 관심을 갖게 하려면?

1. 스크롤 50% 이내에서 핵심 컨텐츠가 보여야 함
- [x] 레이아웃 관리자에 구글 옵티마이즈 태그 설정 추가
- [x] MOB 메인 페이지에서 주제별 섹션을 최하단에서 브랜드뉴스 아래로 이동 by 구글 옵티마이즈
- [x] PC 메인 페이지에서 주제별 섹션을 최하단에서 브랜드뉴스 아래로 이동 by 구글 옵티마이즈

2. 노출된 핵심 컨텐츠가 engage 할 만 해야 함.
- [x] 메인 페이지 목록 위젯이 수정 순으로 추출하도록 변경
- [x] 메인 페이지의 각 섹션 제목을 관리자에서 수정하도록 개선
- [x] 개별 포스팅에 조회수 작성일 표시
- [x] 구 홈피의 모든 컨텐츠를 복붙해서 재작성이 필요한 컨텐츠 목록 추출
- [x] 구 홈피에서 추출한 컨텐츠에 주차별 태그 부여
- [ ] #49 
- [ ] 새로운 컨텐츠 작성 #20
- [ ] 새로운 컨텐츠 작성 #26 
- [ ] 새로운 컨텐츠 작성 #27
- [ ] 새로운 컨텐츠 작성 #28
- [ ] 새로운 컨텐츠 작성 #29

**Comment by singleview-co-kr** [comment]
메인 페이지 목록 위젯이 수정 순으로 추출하도록 변경

**Comment by singleview-co-kr** [comment]
메인 페이지의 각 섹션 제목을 관리자에서 수정하도록 개선

**Comment by singleview-co-kr** [comment]
개별 포스팅에 조회수 작성일 표시

**Comment by ainhye** [comment]
[컨텐츠 리스트]
https://docs.google.com/spreadsheets/d/1srKtU48kY4OKznRLsSrLe-SdGD3pPU3BenxmqBLH5gk/edit#gid=742825065

*포함내용
1) 초기 테스트 선정 컨텐츠
2) 향후운영 할 카테고리 별 컨텐츠 분류
3) 테스트 컨텐츠 및 제작 목표 컨텐츠 선정을 위한 키워드 분석

**Comment by ainhye** [comment]
아래와 같이 두개의 큰 카테고리와 각각 6개의 하위 카테고리로 나누어 기존 웹사이트 컨텐츠 150여개 복붙완료.

[임신/출산]
0) 임신 개월 별 신체변화
1) 임신 준비
2) 임산부 건강/태교
3) 임산부 주의할 것
4) 출산 준비
5) 산후조리/관리


[아기성장/건강]
0) 월령별 아기 성장	
1) 신생아 관리	
2) 신생아 건강	
3) 모유수유	
4) 육아 아이템 (예정)	
5) 이유식 (예정)


제외한 컨텐츠 :
1) 너무 오래되어 제품정보 업데이트가 필요한 컨텐츠
2) 1~2년 주기로 제목만 바꾸어 같은 내용을 업로드 하여 중복된 컨텐츠
3) 본문의 이미지가 날라가서 썸네일로도 쓸 이미지가 없는 컨텐츠
